### ISSUE TITLE
Removes spaces between classes

### ISSUE THREAD

**Issue by dennisfrank** [iksi/kirby-compress#14] opened 2017-04-12 07:12 UTC
I often use two spaces to separate classes from each other. _Compress_ strips all spaces away.

Original:

    <div class="foo  bar"> 

Compressed:

    <div class="foobar">

**Comment by jenstornell** [comment] 2017-04-12 07:30
Why do you use two spaces, why not just a single space? But I agree that it should not remove both of the spaces.

**Comment by dennisfrank** [comment] 2017-04-12 07:37
I just like it. ;) ([And I am not the only one](http://cssguidelin.es/#meaningful-whitespace))

But please, let’s not discuss this now and here. ;)

**Comment by jenstornell** [comment] 2017-04-12 07:40
Possible duplicate of https://github.com/iksi/KirbyCompress/issues/13

**Comment by iksi** [comment] 2017-04-29 10:30
Yes it’s a duplicate. There could be two solutions for this:
1. Either a change to the regex to make it only look for whitespace between tags.
2. Simply change  the `preg_replace` to `preg_replace($pattern, ' ', $input)` so that a single space is being used instead of stripping all the whitespace.

**Comment by iksi** [comment] 2017-12-05 17:34
The issue is quite tricky and for now I chose to replace whitespace with a single space. That way this won’t happen.

**Closed as completed by iksi** 2017-12-05 17:34 UTC
Labels: bug
